// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:9a05abba-1047-48b8-a28a-fbb0c3324318",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_0mDEePp24",
    "aws_user_pools_web_client_id": "5n248b6lsunsie4gnrm5r8lf49",
    "aws_appsync_graphqlEndpoint": "https://3fofcjjpxzahpdwvuhh6jx32mu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
